const PDFDocument = require("pdfkit");

exports.generateBusinessPdf = (title = "Business Listings", listings = []) => {
  return new Promise((resolve) => {
    if (!Array.isArray(listings)) listings = [];

    const doc = new PDFDocument({ margin: 40, size: "A4" });
    const buffers = [];

    doc.on("data", buffers.push.bind(buffers));
    doc.on("end", () => resolve(Buffer.concat(buffers)));

    // 🧾 Header
    doc
      .fontSize(22)
      .fillColor("#1f4fd8")
      .text("Servizio", { align: "center" });
    doc
      .fontSize(16)
      .fillColor("#000")
      .text(title, { align: "center" });

    doc.moveDown(1.5);

    if (listings.length === 0) {
      doc.fontSize(14).text("No business listings found.", { align: "center" });
      doc.end();
      return;
    }

    listings.forEach((b, i) => {
      const name = b.name || "N/A";
      const rating = b.ratings?.overall ?? 0;
      const total = b.ratings?.total ?? 0;

      const statusText =
        b.status === "Verified" ? "Verified" : "Not Verified";
      const trendingText = b.claimed ? "Trending" : "";

      const desc = b.overview?.description || "";
      const minCap = b.overview?.capacity?.minGuests;
      const maxCap = b.overview?.capacity?.maxGuests;
      const price = b.overview?.priceRange || "";
      const availableFor = b.overview?.availableFor?.join(", ") || "";
      const facilities = b.overview?.facilities?.join(", ") || "";

      const address =
        b.locationDetails?.address ||
        b.overview?.addressDetails?.line2 ||
        "";
      const area = b.locationDetails?.area || "";
      const city = b.locationDetails?.city || "";
      const pincode = b.locationDetails?.pincode || "";

      const phone = b.contactDetails?.phone || "N/A";
      const whatsapp = b.contactDetails?.whatsapp || "N/A";
      const email = b.contactDetails?.email || "N/A";

      const hours =
        b.operatingHours || b.overview?.openingHours || "";

      // 🟦 Business Title
      doc
        .fontSize(15)
        .fillColor("#000")
        .text(`${i + 1}. ${name}`, { underline: true });

      doc
        .moveDown(0.2)
        .fontSize(11)
        .fillColor("#333")
        .text(`Rating: ${rating} (${total} ratings)`)
        .text(`Status: ${statusText}${trendingText ? " | " + trendingText : ""}`);

      if (desc) doc.text(`About: ${desc}`);

      if (minCap && maxCap)
        doc.text(`Capacity: ${minCap} - ${maxCap} Guests`);

      if (price) doc.text(`Price Range: ${price}`);

      if (availableFor)
        doc.text(`Suitable For: ${availableFor}`);

      if (facilities)
        doc.text(`Facilities: ${facilities}`);

      if (address) doc.text(`Address: ${address}`);
      doc.text(`Location: ${area}, ${city} - ${pincode}`);

      doc
        .text(`Phone: ${phone}`)
        .text(`WhatsApp: ${whatsapp}`)
        .text(`Email: ${email}`);

      if (hours) doc.text(`Hours: ${hours}`);

      doc.moveDown(0.6);

      // Divider line
      doc
        .strokeColor("#cccccc")
        .lineWidth(1)
        .moveTo(40, doc.y)
        .lineTo(555, doc.y)
        .stroke();

      doc.moveDown(0.8);
    });

    // Footer
    doc
      .moveDown(2)
      .fontSize(10)
      .fillColor("gray")
      .text(
        `Generated by Servizio • ${new Date().toLocaleString()}`,
        { align: "center" }
      );

    doc.end();
  });
};
